### ISSUE TITLE
Failing with CLang/XCode 5

### ISSUE THREAD

**Issue by aledalgrande** [patmarion/pcl-superbuild#7]
I tried compiling for iOS with the latest dev libraries, but it fails on the Boost library, there is a declaration that conflicts with the Vector in the C++ standard library. This problem has been fixed in recent versions of Boost, but this version seems to be patched, so not easy to use a newer one. I'm trying to integrate Boost 1.55.0 for iOS, but I'm getting warnings like this one, even if I passed flags like `-stdlib=libc++`:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: libboost_date_time.a(gregorian_types.cpp.o) has no symbols
```
Don't know how to fix it. Is this the only way of building PCL for iOS? I tried the precompiled frameworks, but they throw errors when imported in XCode.

**Comment by lironsam** [comment]
@aledalgrande Did you manage to compile properly PCL on iOS ?
I'm still struggling about it...

**Comment by aledalgrande** [comment]
@lilouch nope sorry, I rolled my own solution.

**Comment by lironsam** [comment]
Could you explain me more about your own solution ? Maybe a clue ? 
I really need to use PCL with iOS.

Thank you very much in advance @aledalgrande

**Comment by aledalgrande** [comment]
@lilouch sorry, just means I didn't use PCL at all, I did my own coding for the algorithms and visualization.
